name: Go Test

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - go.mod
      - go.sum
      - storage/**
      - testhelpers/**
      - version/**

env:
  GO_VERSION: "1.14.4"

jobs:
  go_mod_download:
    name: go mod download
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - run: go mod download
